services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12.12-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-volume:/var/lib/rabbitmq

volumes:
  rabbitmq-volume: